- name: Running to check system performance
  hosts: all
  tasks:
  - name: Run disk utility
    ansible.builtin.shell: df -h
    register: DISKUTIL
  - name: printing disk utility
    ansible.builtin.debug:
     msg:  "{{ DISKUTIL.stdout_lines | join('\n') }}"
  - name: Run RAM untlity
    ansible.builtin.shell: free
    register: RAMUTIL
  - name: printing RAM untlity
    ansible.builtin.debug:
     msg: |-
       {{ RAMUTIL.stdout_lines | join('\n') }}
    
  - name: Run processor utility
    ansible.builtin.shell: nproc
    register: PROCESSORUTIL
  - name: processor utility
    ansible.builtin.debug:
     msg: |-
        {{ PROCESSORUTIL.stdout }}

    