- name: file vars
  hosts: all
  vars_files:
   - "{{ env }}-vars.yaml"
  tasks:
  - name: check the ip
    ansible.builtin.shell: ifconfig
    register: IFCONFIG
  - name: print ip info
    ansible.builtin.debug:
     msg: "{{ IFCONFIG }} this is {{ STAGE }}-vars.yaml which manage by {{ DEVLEAD }}"
