- name: file vars
  hosts: dev
  vars_file:
  - "{{ stage }}-vars.yaml"
  tasks:
  - name: check the ip
    ansible.builtin.shell: ifconfig
    register: IFCONFIG
  - name: print ip info
    ansible.builtin.debug:
     msg: "{{ IFCONFIG }} this is {{ stage }}-vars.yaml which manage by {{ devlead }}"
